
/* =========================================================
Investment Portfolio Analytics & Trade Data Warehouse
Business_Queries.sql
========================================================= */

/* Q1. Which companies have the highest number of trades? */
SELECT c.Company_Name, COUNT(*) AS Total_Trades
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID = c.Company_ID
GROUP BY c.Company_Name
ORDER BY Total_Trades DESC;

/* Q2. Which investors executed the most trades? */
SELECT i.Investor_ID, i.First_Name, i.Last_Name, COUNT(*) AS Total_Trades
FROM Fact_Trades ft
JOIN Trading_Accounts ta ON ft.Account_ID = ta.Account_ID
JOIN Investors i ON ta.Investor_ID = i.Investor_ID
GROUP BY i.Investor_ID, i.First_Name, i.Last_Name
ORDER BY Total_Trades DESC;

/* Q3. Which brokers handled the most trades? */
SELECT b.Broker_Name, COUNT(*) AS Total_Trades
FROM Fact_Trades ft
JOIN Brokers b ON ft.Broker_ID=b.Broker_ID
GROUP BY b.Broker_Name
ORDER BY Total_Trades DESC;

/* Q4. What is the total trade volume per company? */
SELECT c.Company_Name,SUM(ft.No_of_shares) AS Trade_Volume
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Company_Name;

/* Q5. What is the total trade value per company? */
SELECT c.Company_Name,
SUM(ft.No_of_shares*ft.Price_share) AS Trade_Value
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Company_Name;

/* Q6. Which sectors attract the highest trading activity? */
SELECT c.Sector,COUNT(*) AS Trade_Count
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Sector
ORDER BY Trade_Count DESC;

/* Q7. What is the average trade size by company? */
SELECT c.Company_Name,AVG(ft.No_of_shares) Avg_Trade_Size
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Company_Name;

/* Q8. What is the average trade value by investor? */
SELECT i.Investor_ID,
AVG(ft.No_of_shares*ft.Price_share) Avg_Trade_Value
FROM Fact_Trades ft
JOIN Trading_Accounts ta ON ft.Account_ID=ta.Account_ID
JOIN Investors i ON ta.Investor_ID=i.Investor_ID
GROUP BY i.Investor_ID;

/* Q9. Which investors trade most frequently? */
SELECT TOP 10 i.Investor_ID,i.First_Name,i.Last_Name,COUNT(*) Trades
FROM Fact_Trades ft
JOIN Trading_Accounts ta ON ft.Account_ID=ta.Account_ID
JOIN Investors i ON ta.Investor_ID=i.Investor_ID
GROUP BY i.Investor_ID,i.First_Name,i.Last_Name
ORDER BY Trades DESC;

/* Q10. Which brokers manage the largest number of accounts? */
SELECT b.Broker_Name,COUNT(*) Accounts
FROM Trading_Accounts ta
JOIN Brokers b ON ta.Broker_ID=b.Broker_ID
GROUP BY b.Broker_Name
ORDER BY Accounts DESC;

/* Q11. Which companies have the highest dividend yield? */
SELECT c.Company_Name,AVG(d.Dividend_Yield) Avg_Yield
FROM Dividends d
JOIN Companies c ON d.Company_ID=c.Company_ID
GROUP BY c.Company_Name
ORDER BY Avg_Yield DESC;

/* Q12. Which companies paid the most total dividends? */
SELECT c.Company_Name,SUM(d.Dividend_Per_Share) Total_Dividends
FROM Dividends d
JOIN Companies c ON d.Company_ID=c.Company_ID
GROUP BY c.Company_Name
ORDER BY Total_Dividends DESC;

/* Q13. What is the total dividend income generated by each company? */
SELECT c.Company_Name,SUM(d.Dividend_Per_Share) Dividend_Income
FROM Dividends d
JOIN Companies c ON d.Company_ID=c.Company_ID
GROUP BY c.Company_Name;

/* Q14. Which investors hold the largest portfolio value? */
SELECT i.Investor_ID,i.First_Name,i.Last_Name,
SUM(ph.Market_Value) Portfolio_Value
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
JOIN Investors i ON ta.Investor_ID=i.Investor_ID
GROUP BY i.Investor_ID,i.First_Name,i.Last_Name
ORDER BY Portfolio_Value DESC;

/* Q15. Which investors hold the highest number of companies? */
SELECT i.Investor_ID,COUNT(DISTINCT ph.Company_ID) Company_Count
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
JOIN Investors i ON ta.Investor_ID=i.Investor_ID
GROUP BY i.Investor_ID
ORDER BY Company_Count DESC;

/* Q16. What is the portfolio distribution by sector? */
SELECT c.Sector,SUM(ph.Market_Value) Portfolio_Value
FROM Portfolio_Holdings ph
JOIN Companies c ON ph.Company_ID=c.Company_ID
GROUP BY c.Sector;

/* Q17. What is the average portfolio value by investor? */
SELECT i.Investor_ID,AVG(ph.Market_Value) Avg_Portfolio_Value
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
JOIN Investors i ON ta.Investor_ID=i.Investor_ID
GROUP BY i.Investor_ID;

/* Q18. Which trading accounts have the highest cash movement? */
SELECT TOP 10 Account_ID,SUM(Amount) Total_Cash_Movement
FROM Cash_Transactions
GROUP BY Account_ID
ORDER BY Total_Cash_Movement DESC;

/* Q19. Which stocks generated the highest market value? */
SELECT c.Company_Name,SUM(ph.Market_Value) Market_Value
FROM Portfolio_Holdings ph
JOIN Companies c ON ph.Company_ID=c.Company_ID
GROUP BY c.Company_Name
ORDER BY Market_Value DESC;

/* Q20. What are the top 10 most valuable portfolios? */
SELECT TOP 10 Account_ID,SUM(Market_Value) Portfolio_Value
FROM Portfolio_Holdings
GROUP BY Account_ID
ORDER BY Portfolio_Value DESC;


/* Q21. Find investors whose portfolio value exceeds average portfolio value */
SELECT *
FROM (
    SELECT ta.Investor_ID,SUM(ph.Market_Value) Portfolio_Value
    FROM Portfolio_Holdings ph
    JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
    GROUP BY ta.Investor_ID
) x
WHERE Portfolio_Value >
(
    SELECT AVG(Portfolio_Value)
    FROM (
        SELECT SUM(Market_Value) Portfolio_Value
        FROM Portfolio_Holdings
        GROUP BY Account_ID
    ) y
);

/* Q22. Companies whose trade volume exceeds average */
SELECT Company_ID,SUM(No_of_shares) Volume
FROM Fact_Trades
GROUP BY Company_ID
HAVING SUM(No_of_shares) >
(
    SELECT AVG(Volume)
    FROM (
        SELECT SUM(No_of_shares) Volume
        FROM Fact_Trades
        GROUP BY Company_ID
    ) t
);

/* Q23. Brokers above average trade activity */
SELECT Broker_ID,COUNT(*) Trades
FROM Fact_Trades
GROUP BY Broker_ID
HAVING COUNT(*) >
(
    SELECT AVG(TradeCount)
    FROM (
        SELECT COUNT(*) TradeCount
        FROM Fact_Trades
        GROUP BY Broker_ID
    ) x
);

/* Q24. Investors holding more than 5 companies */
SELECT ta.Investor_ID,
COUNT(DISTINCT ph.Company_ID) Company_Count
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
GROUP BY ta.Investor_ID
HAVING COUNT(DISTINCT ph.Company_ID) > 5;

/* Q25. Companies that never paid dividends */
SELECT Company_ID
FROM Companies
EXCEPT
SELECT Company_ID
FROM Dividends;

/* Q26. Investors who never executed a trade */
SELECT Investor_ID
FROM Investors
EXCEPT
SELECT ta.Investor_ID
FROM Trading_Accounts ta
JOIN Fact_Trades ft
ON ta.Account_ID=ft.Account_ID;

/* Q27. Companies with dividend and price records */
SELECT DISTINCT Company_ID
FROM Dividends
INTERSECT
SELECT DISTINCT Company_ID
FROM Historical_Prices;

/* Q28. Profit/Loss percentage per holding */
SELECT Holding_ID,
((Current_Price-Avg_Buy_Price)/Avg_Buy_Price)*100 AS Return_Percent
FROM Portfolio_Holdings;

/* Q29. Portfolio categorization */
SELECT Holding_ID,
CASE
WHEN Market_Value < 5000 THEN 'Small'
WHEN Market_Value < 25000 THEN 'Medium'
ELSE 'Large'
END Portfolio_Size
FROM Portfolio_Holdings;

/* Q30. Monthly trading activity */
SELECT YEAR(Transaction_Date) Yr,
MONTH(Transaction_Date) Mn,
COUNT(*) Trades
FROM Fact_Trades
GROUP BY YEAR(Transaction_Date),MONTH(Transaction_Date);

/* Q31. Yearly dividend trends */
SELECT YEAR(Dividend_Date) Yr,
SUM(Dividend_Per_Share) Total_Dividend
FROM Dividends
GROUP BY YEAR(Dividend_Date);

/* Q32. Top traded company in each sector */
WITH CTE AS (
SELECT c.Sector,c.Company_Name,
COUNT(*) Trades,
ROW_NUMBER() OVER(PARTITION BY c.Sector ORDER BY COUNT(*) DESC) rn
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Sector,c.Company_Name
)
SELECT *
FROM CTE
WHERE rn=1;

/* Q33. Account-wise net cash flow */
SELECT Account_ID,
SUM(CASE WHEN Transaction_Type='Deposit' THEN Amount ELSE -Amount END) Net_CashFlow
FROM Cash_Transactions
GROUP BY Account_ID;

/* Q34. Company ranking by trade value */
SELECT Company_ID,
SUM(No_of_shares*Price_share) Trade_Value,
RANK() OVER(ORDER BY SUM(No_of_shares*Price_share) DESC) Company_Rank
FROM Fact_Trades
GROUP BY Company_ID;

/* Q35. Concentration risk */
SELECT Account_ID,
MAX(Market_Value)*100.0/SUM(Market_Value) Risk_Percentage
FROM Portfolio_Holdings
GROUP BY Account_ID;

/* Q36. Top 5 investors by portfolio value */
WITH InvestorPortfolio AS (
SELECT ta.Investor_ID,
SUM(ph.Market_Value) Portfolio_Value
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
GROUP BY ta.Investor_ID
)
SELECT TOP 5 *
FROM InvestorPortfolio
ORDER BY Portfolio_Value DESC;

/* Q37. Top traded companies by sector */
WITH TradeCTE AS (
SELECT c.Sector,c.Company_Name,COUNT(*) Trades
FROM Fact_Trades ft
JOIN Companies c ON ft.Company_ID=c.Company_ID
GROUP BY c.Sector,c.Company_Name
)
SELECT *
FROM TradeCTE;

/* Q38. Cumulative cash flow */
WITH CashFlow AS (
SELECT Account_ID,
SUM(Amount) CashFlow
FROM Cash_Transactions
GROUP BY Account_ID
)
SELECT *
FROM CashFlow;

/* Q39. Above average trading volume accounts */
WITH TradeVolume AS (
SELECT Account_ID,COUNT(*) Trades
FROM Fact_Trades
GROUP BY Account_ID
)
SELECT *
FROM TradeVolume
WHERE Trades >
(SELECT AVG(Trades) FROM TradeVolume);

/* Q40. Investor performance summary */
WITH Perf AS (
SELECT ta.Investor_ID,
SUM(ph.Market_Value) ValueHeld
FROM Portfolio_Holdings ph
JOIN Trading_Accounts ta ON ph.Account_ID=ta.Account_ID
GROUP BY ta.Investor_ID
)
SELECT *
FROM Perf;

/* Q41. Rank companies by trade value */
SELECT Company_ID,
SUM(No_of_shares*Price_share) TradeValue,
RANK() OVER(ORDER BY SUM(No_of_shares*Price_share) DESC) Ranking
FROM Fact_Trades
GROUP BY Company_ID;

/* Q42. Top investors by state */
SELECT State,Investor_ID,
DENSE_RANK() OVER(PARTITION BY State ORDER BY Investor_ID) RankNum
FROM Investors;

/* Q43. Running trade value */
SELECT Transaction_Date,
SUM(No_of_shares*Price_share)
OVER(ORDER BY Transaction_Date) Running_Value
FROM Fact_Trades;

/* Q44. Running portfolio value */
SELECT Account_ID,
SUM(Market_Value)
OVER(PARTITION BY Account_ID ORDER BY Last_Updated) Running_Portfolio
FROM Portfolio_Holdings;

/* Q45. Compare current vs previous price */
SELECT Company_ID,Price_Date,Close_Price,
LAG(Close_Price) OVER(PARTITION BY Company_ID ORDER BY Price_Date) Prev_Price
FROM Historical_Prices;

/* Q46. Price growth percentage */
SELECT Company_ID,Price_Date,
((Close_Price - LAG(Close_Price) OVER(PARTITION BY Company_ID ORDER BY Price_Date))
/
LAG(Close_Price) OVER(PARTITION BY Company_ID ORDER BY Price_Date))*100 GrowthPct
FROM Historical_Prices;

/* Q47. Next dividend date */
SELECT Company_ID,Dividend_Date,
LEAD(Dividend_Date) OVER(PARTITION BY Company_ID ORDER BY Dividend_Date) Next_Dividend
FROM Dividends;

/* Q48. Highest and lowest price days */
SELECT Company_ID,
MAX(Close_Price) Highest_Price,
MIN(Close_Price) Lowest_Price
FROM Historical_Prices
GROUP BY Company_ID;

/* Q49. Investor percentile ranking */
SELECT Account_ID,Market_Value,
NTILE(4) OVER(ORDER BY Market_Value DESC) Quartile
FROM Portfolio_Holdings;

/* Q50. Moving average stock price */
SELECT Company_ID,Price_Date,Close_Price,
AVG(Close_Price)
OVER(PARTITION BY Company_ID ORDER BY Price_Date
ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) Moving_Avg
FROM Historical_Prices;

